import { env } from "@/lib/env";

export const siteConfig = {
  name: "C. John Remthang",
  shortName: "cjohnmizo",
  publicIdentityLabels: ["C. John", "CJohn Mizo", "cjohnmizo"],
  alternateNames: ["C. John", "CJohn Mizo", "C John Remthang", "John Remthang"],
  domain: "cjohnmizo.in",
  url: env.NEXT_PUBLIC_SITE_URL,
  title: "C. John Remthang | Cinematic Dashboard, LMS & Web Developer",
  description:
    "Portfolio of C. John Remthang, a Mizoram-based developer building cinematic dashboard interfaces, LMS platforms, mobile apps, websites, and practical digital systems.",
  keywords: [
    "C. John Remthang",
    "C John Remthang",
    "C. John",
    "C John",
    "CJohn Mizo",
    "John Remthang",
    "cjohnmizo",
    "cjohnmizo.in",
    "full-stack developer",
    "software engineer",
    "Next.js portfolio",
    "TypeScript developer",
    "developer portfolio",
    "Mizoram developer",
    "cinematic dashboard developer",
    "LMS developer",
    "dashboard developer",
    "school website developer",
    "NGO software",
    "mobile app developer",
    "Laravel developer",
    "Flutter developer",
  ],
  locale: "en_US",
  securityEmail: "contact@cjohnmizo.in",
  defaultOgImage: "/brand/cjohnmizo-favicon.png",
  navItems: [
    { label: "About", href: "/about" },
    { label: "Systems", href: "/#systems" },
    { label: "Projects", href: "/projects" },
    { label: "Experience", href: "/#experience" },
    { label: "Contact", href: "/#contact" },
  ],
};
