import { env } from "@/lib/env";

export const siteConfig = {
  name: "C. John Remthang",
  shortName: "cjohnmizo",
  publicIdentityLabels: ["C. John", "CJohn Mizo", "cjohnmizo"],
  alternateNames: ["C. John", "CJohn Mizo", "C John Remthang", "John Remthang"],
  domain: "cjohnmizo.in",
  url: env.NEXT_PUBLIC_SITE_URL,
  title: "C. John Remthang | Web, LMS, Dashboard & Mobile App Developer",
  description:
    "Personal portfolio of C. John Remthang, a Mizoram-based developer building practical websites, LMS platforms, dashboards, mobile apps, and digital systems for schools, NGOs, businesses, and communities.",
  keywords: [
    "C. John Remthang",
    "C John Remthang",
    "C. John",
    "C John",
    "CJohn Mizo",
    "John Remthang",
    "cjohnmizo",
    "cjohnmizo.in",
    "full-stack developer",
    "software engineer",
    "Next.js portfolio",
    "TypeScript developer",
    "developer portfolio",
    "Mizoram developer",
    "LMS developer",
    "dashboard developer",
    "admin dashboard developer",
    "Firebase developer",
    "Kotlin developer",
    "UI UX redesign",
    "school website developer",
    "NGO software",
    "community systems",
    "mobile app developer",
    "Laravel developer",
    "Flutter developer",
  ],
  locale: "en_US",
  securityEmail: env.CONTACT_PUBLIC_EMAIL,
  defaultOgImage: "/brand/cjohnmizo-favicon.png",
  navItems: [
    { label: "About", href: "/about" },
    { label: "Systems", href: "/#services" },
    { label: "Projects", href: "/projects" },
    { label: "Process", href: "/#process" },
    { label: "Contact", href: "/#contact" },
  ],
};
